# -*- coding: utf-8 -*-
"""digitalFireworksDisplay.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mSLiZJjWZyNME2wbPB6Kjxz5TXaGeTrL
"""

import pygame
import random
import math

# Initialize Pygame
pygame.init()

# Constants
WIDTH, HEIGHT = 800, 600
FPS = 60
BACKGROUND_COLOR = (0, 0, 0)
FIREWORK_COLORS = [(255, 0, 0), (0, 255, 0), (0, 0, 255), (255, 255, 0), (255, 0, 255), (0, 255, 255)]
GRAVITY = 0.5

# Initialize the screen
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Digital Fireworks")

# Firework particle class
class Particle:
    def __init__(self, x, y, color):
        self.x = x
        self.y = y
        self.color = color
        self.radius = random.randint(2, 6)
        self.angle = random.uniform(0, 2 * math.pi)
        self.speed = random.uniform(2, 6)
        self.gravity = GRAVITY
        self.lifespan = random.randint(30, 60)

    def update(self):
        self.x += math.cos(self.angle) * self.speed
        self.y += math.sin(self.angle) * self.speed + self.gravity
        self.speed -= 0.1
        self.lifespan -= 1

    def draw(self):
        pygame.draw.circle(screen, self.color, (int(self.x), int(self.y)), self.radius)

# Main loop
clock = pygame.time.Clock()
running = True
particles = []

while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

    screen.fill(BACKGROUND_COLOR)

    if random.random() < 0.02:
        x, y = random.randint(100, WIDTH - 100), HEIGHT
        color = random.choice(FIREWORK_COLORS)
        for _ in range(100):
            particles.append(Particle(x, y, color))

    for particle in particles:
        particle.update()
        particle.draw()

    particles = [p for p in particles if p.lifespan > 0]

    pygame.display.flip()
    clock.tick(FPS)

# Quit Pygame
pygame.quit()